// Generated by gencpp from file package1/Nav.msg
// DO NOT EDIT!


#ifndef PACKAGE1_MESSAGE_NAV_H
#define PACKAGE1_MESSAGE_NAV_H

#include <ros/service_traits.h>


#include <package1/NavRequest.h>
#include <package1/NavResponse.h>


namespace package1
{

struct Nav
{

typedef NavRequest Request;
typedef NavResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Nav
} // namespace package1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::package1::Nav > {
  static const char* value()
  {
    return "ecf3a247110a76fb77a2db5d9c8c5101";
  }

  static const char* value(const ::package1::Nav&) { return value(); }
};

template<>
struct DataType< ::package1::Nav > {
  static const char* value()
  {
    return "package1/Nav";
  }

  static const char* value(const ::package1::Nav&) { return value(); }
};


// service_traits::MD5Sum< ::package1::NavRequest> should match 
// service_traits::MD5Sum< ::package1::Nav > 
template<>
struct MD5Sum< ::package1::NavRequest>
{
  static const char* value()
  {
    return MD5Sum< ::package1::Nav >::value();
  }
  static const char* value(const ::package1::NavRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::package1::NavRequest> should match 
// service_traits::DataType< ::package1::Nav > 
template<>
struct DataType< ::package1::NavRequest>
{
  static const char* value()
  {
    return DataType< ::package1::Nav >::value();
  }
  static const char* value(const ::package1::NavRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::package1::NavResponse> should match 
// service_traits::MD5Sum< ::package1::Nav > 
template<>
struct MD5Sum< ::package1::NavResponse>
{
  static const char* value()
  {
    return MD5Sum< ::package1::Nav >::value();
  }
  static const char* value(const ::package1::NavResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::package1::NavResponse> should match 
// service_traits::DataType< ::package1::Nav > 
template<>
struct DataType< ::package1::NavResponse>
{
  static const char* value()
  {
    return DataType< ::package1::Nav >::value();
  }
  static const char* value(const ::package1::NavResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PACKAGE1_MESSAGE_NAV_H
