// Generated by gencpp from file package1/NavResponse.msg
// DO NOT EDIT!


#ifndef PACKAGE1_MESSAGE_NAVRESPONSE_H
#define PACKAGE1_MESSAGE_NAVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package1
{
template <class ContainerAllocator>
struct NavResponse_
{
  typedef NavResponse_<ContainerAllocator> Type;

  NavResponse_()
    : p(0)  {
    }
  NavResponse_(const ContainerAllocator& _alloc)
    : p(0)  {
  (void)_alloc;
    }



   typedef int64_t _p_type;
  _p_type p;





  typedef boost::shared_ptr< ::package1::NavResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package1::NavResponse_<ContainerAllocator> const> ConstPtr;

}; // struct NavResponse_

typedef ::package1::NavResponse_<std::allocator<void> > NavResponse;

typedef boost::shared_ptr< ::package1::NavResponse > NavResponsePtr;
typedef boost::shared_ptr< ::package1::NavResponse const> NavResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package1::NavResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package1::NavResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace package1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'package1': ['/home/sabrino/exprob/exprob1_ws/src/package1/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::package1::NavResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package1::NavResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package1::NavResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package1::NavResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package1::NavResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package1::NavResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package1::NavResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc79ae4c06a8a778f1823c93d70f35d2";
  }

  static const char* value(const ::package1::NavResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc79ae4c06a8a778ULL;
  static const uint64_t static_value2 = 0xf1823c93d70f35d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::package1::NavResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package1/NavResponse";
  }

  static const char* value(const ::package1::NavResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package1::NavResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 p\n\
\n\
";
  }

  static const char* value(const ::package1::NavResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package1::NavResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package1::NavResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package1::NavResponse_<ContainerAllocator>& v)
  {
    s << indent << "p: ";
    Printer<int64_t>::stream(s, indent + "  ", v.p);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE1_MESSAGE_NAVRESPONSE_H
