// Generated by gencpp from file package1/Position.msg
// DO NOT EDIT!


#ifndef PACKAGE1_MESSAGE_POSITION_H
#define PACKAGE1_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package1
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : x(0)
    , y(0)  {
    }
  Position_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef uint64_t _x_type;
  _x_type x;

   typedef uint64_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::package1::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package1::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::package1::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::package1::Position > PositionPtr;
typedef boost::shared_ptr< ::package1::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package1::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package1::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace package1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'package1': ['/home/sabrino/exprob/exprob1_ws/src/package1/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::package1::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package1::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package1::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package1::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package1::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package1::Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package1::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c840954fabcd833a6e0d0435ab12e8d0";
  }

  static const char* value(const ::package1::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc840954fabcd833aULL;
  static const uint64_t static_value2 = 0x6e0d0435ab12e8d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::package1::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package1/Position";
  }

  static const char* value(const ::package1::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package1::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
uint64 x\n\
uint64 y\n\
";
  }

  static const char* value(const ::package1::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package1::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package1::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package1::Position_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE1_MESSAGE_POSITION_H
